# Generated by Django 4.2 on 2023-05-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colonne',
            fields=[
                ('id_colonne', models.AutoField(primary_key=True, serialize=False)),
                ('titre_colonne', models.CharField(max_length=250)),
                ('position_colonne', models.IntegerField()),
            ],
            options={
                'db_table': 'colonne',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id_tache', models.AutoField(primary_key=True, serialize=False)),
                ('titre_tache', models.CharField(max_length=250)),
                ('position_tache', models.IntegerField()),
                ('colonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='app.colonne')),
            ],
            options={
                'db_table': 'tache',
                'managed': True,
            },
        ),
    ]
